package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/smmd/giveaway-2021/repository"
	"github.com/smmd/giveaway-2021/utils"
)

func main()  {
	var filePath string
	userNames := []string{}

	fmt.Print("Enter the file name: ")

	_, err := fmt.Scanf("%s", &filePath)

	if err != nil {
		panic(fmt.Errorf("could not read Path: %w", err))
	}

	file, err := os.Open(filePath)

	if err != nil {
		log.Fatalf("failed to open file error: %v", err)

	}

	scanner := bufio.NewScanner(file)

	scanner.Split(bufio.ScanLines)
	var text []string

	for scanner.Scan() {
		text = append(text, scanner.Text())
	}

	file.Close()

	for _, line := range text {
		userData := &repository.AutoGenerated{}

		byt := []byte(line)
		err = json.Unmarshal(byt, userData)

		if err != nil {
			log.Fatalf("could not process line file error: %v", err)
		} else {
			prettyResult, err := utils.PrettyStruct(userData)
			if err != nil {
				panic(err)
			}

			//userNames = append(userNames, userData.)

			fmt.Printf("User Data:\n%s", prettyResult)
		}
	}
}
